### ISSUE TITLE
Crashes with ValueError

### ISSUE THREAD

**Issue by osovv** [osovv/miet-schedule#1]
Sometimes when I run app it crashes with this error.
```
Traceback (most recent call last):
  File "/home/al/.local/src/repos/miet-schedule/Parser.py", line 182, in <module>
    parser.parse_table_header()
  File "/home/al/.local/src/repos/miet-schedule/Parser.py", line 130, in parse_table_header
    th_date, th_day_name = th.text.split(' ')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by osovv** [comment]
It happens because sometimes schedule type is not choosen properly.

**Comment by osovv** [comment]
For some reason button used to change schedule type is not always clicked. It seems that line doesnt' work properly:
```WebDriverWait(self.driver, 20).until(EC.element_to_be_clickable((By.XPATH, xpath))).click()```
It should wait until element is clickable and then click on it, but it doesn't. Need to figure this out.
